"use strict";
exports.__esModule = true;
exports.newCasino = exports.progressiveSlot1 = exports.reelSlot1 = void 0;
var progressiveSlot_1 = require("./class/progressiveSlot");
var reelSlot_1 = require("./class/reelSlot");
var casino_1 = require("./class/casino");
var progressiveSlotBet = [1, 2, 5, 10, 15];
var reelSlotBet = [5, 10, 15, 20];
exports.reelSlot1 = new reelSlot_1.ReelSlot(1001, reelSlotBet, "Animal", 15, 20, 3, 10000);
exports.progressiveSlot1 = new progressiveSlot_1.ProgressiveSlot(2001, progressiveSlotBet, "Egipcio", 40, 25, 5, 5, 500000);
var reelSlotList = [exports.reelSlot1];
var progressiveSlotList = [exports.progressiveSlot1];
exports.newCasino = new casino_1.Casino('Atlanta', progressiveSlotList, reelSlotList, 500000);
